(() => {
  "use strict";
  const URL_SERVICO = "https://otvnhahpwblgxevzrsra.supabase.co";
  const CHAVE_PUBLICA = "sb_publishable_OpslVSpJubk6OCLQzand-A_KkeLfQ6r";
  if (!window.supabase?.createClient) return;
  const db = window.supabase.createClient(URL_SERVICO, CHAVE_PUBLICA, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:"simulador_sessao"}});
  const $=s=>document.querySelector(s),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  let historico=[],tentativas=[];
  const recursos=[
    ["🏛️","Escola Virtual de Governo","Administração pública, ética, legislação e gestão.","https://www.escolavirtual.gov.br/"],
    ["💻","Fundação Bradesco — Escola Virtual","Informática, administração e produtividade.","https://www.ev.org.br/"],
    ["➗","Khan Academy","Matemática, estatística e raciocínio quantitativo.","https://pt.khanacademy.org/"],
    ["🖥️","Curso em Vídeo","Informática e fundamentos digitais em aulas gratuitas.","https://www.cursoemvideo.com/"],
    ["✍️","Professor Noslen","Português, gramática, interpretação e redação.","https://www.youtube.com/@ProfessorNoslen"],
    ["📝","PCI Concursos — Provas","Provas anteriores para treino por banca e órgão.","https://www.pciconcursos.com.br/provas/"],
    ["⚖️","Portal da Legislação","Consulta gratuita a leis e textos oficiais.","https://www4.planalto.gov.br/legislacao"],
    ["🎥","YouTube Educação","Buscas por matéria, banca e edital.","https://www.youtube.com/"],
    ["📚","Domínio Público","Livros e materiais gratuitos para leitura.","https://www.dominiopublico.gov.br/"]
  ];
  const inicioHoje=()=>{const d=new Date();d.setHours(0,0,0,0);return d},fimHoje=()=>{const d=new Date();d.setHours(23,59,59,999);return d};
  function duracao(s){s=Number(s||0);return s<3600?`${Math.round(s/60)} min`:`${Math.floor(s/3600)}h ${Math.round((s%3600)/60)}min`}
  function inicioSemana(d){const x=new Date(d),dia=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-dia);return x}
  function renderRecursos(){const b=$("#lista-recursos");if(b)b.innerHTML=recursos.map(r=>`<a class="recurso-card" href="${r[3]}" target="_blank" rel="noopener noreferrer"><span>${r[0]}</span><b>${esc(r[1])}</b><small>${esc(r[2])}</small></a>`).join("")}
  function aplicarMarcadas(){const grade=$("#grade-questoes");if(!grade||!window.Simulador?.CHAVE_PROGRESSO)return;try{const p=JSON.parse(localStorage.getItem(window.Simulador.CHAVE_PROGRESSO)),m=new Set((p?.marcadas||[]).map(String));grade.querySelectorAll("button.numero").forEach((b,i)=>{const id=p?.questoes?.[i]?.id;b.classList.toggle("marcada-visible",id!==undefined&&m.has(String(id)));if(id!==undefined&&m.has(String(id)))b.title="Questão marcada para revisar"})}catch{}}
  function renderHoje(){const ini=inicioHoje(),fim=fimHoje(),h=tentativas.filter(t=>{const d=new Date(t.concluido_em);return d>=ini&&d<=fim}),q=h.reduce((s,x)=>s+Number(x.total||0),0),a=h.reduce((s,x)=>s+Number(x.acertos||0),0),tempo=h.reduce((s,x)=>s+Number(x.tempo_segundos||0),0);$("#hoje-data").textContent=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(new Date());$("#hoje-questoes").textContent=q;$("#hoje-acertos").textContent=a;$("#hoje-media").textContent=`${q?Math.round(a/q*100):0}%`;$("#hoje-tempo").textContent=duracao(tempo)}
  function renderGerais(){const corte=inicioHoje(),base=tentativas.filter(t=>new Date(t.concluido_em)<corte),sem=inicioSemana(new Date()),atual=base.filter(t=>new Date(t.concluido_em)>=sem),q=atual.reduce((s,x)=>s+Number(x.total||0),0),a=atual.reduce((s,x)=>s+Number(x.acertos||0),0),tempo=atual.reduce((s,x)=>s+Number(x.tempo_segundos||0),0);$("#kpi-questoes").textContent=q;$("#kpi-media").textContent=`${q?Math.round(a/q*100):0}%`;$("#kpi-tempo").textContent=duracao(tempo);$("#resumo-periodo").textContent=q?`Sem contar hoje, você respondeu ${q} questões nesta semana.`:"Os indicadores gerais abaixo não incluem a atividade de hoje.";const nomes=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"],g=$("#grafico-semanal");if(g)g.innerHTML=nomes.map((n,i)=>{const d=new Date(sem);d.setDate(d.getDate()+i);const f=new Date(d);f.setDate(f.getDate()+1);const itens=base.filter(t=>new Date(t.concluido_em)>=d&&new Date(t.concluido_em)<f),tq=itens.reduce((s,x)=>s+Number(x.total||0),0),ta=itens.reduce((s,x)=>s+Number(x.acertos||0),0),p=tq?Math.round(ta/tq*100):0;return`<div class="barra-dia" title="${p}%"><div class="barra-dia__coluna"><span class="barra-dia__valor" style="height:${p}%"></span></div><small>${n}<br>${p}%</small></div>`}).join("");const meses=[];for(let i=5;i>=0;i--){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);d.setHours(0,0,0,0);const f=new Date(d);f.setMonth(f.getMonth()+1);const itens=base.filter(t=>new Date(t.concluido_em)>=d&&new Date(t.concluido_em)<f),tq=itens.reduce((s,x)=>s+Number(x.total||0),0),ta=itens.reduce((s,x)=>s+Number(x.acertos||0),0);meses.push({nome:new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(d).replace(".",""),pct:tq?Math.round(ta/tq*100):0})}const gm=$("#grafico-mensal-extra");if(gm)gm.innerHTML=meses.map(m=>`<div class="mes-coluna"><div class="mes-coluna__area"><span class="mes-coluna__barra" style="height:${m.pct}%"></span></div><small>${esc(m.nome)}<br><b>${m.pct}%</b></small></div>`).join("")}
  function filtrados(){const termo=($("#busca-historico")?.value||"").toLowerCase(),f=$("#filtro-resultado")?.value||"todos";return historico.filter(x=>(!termo||`${x.materia} ${x.assunto} ${x.enunciado}`.toLowerCase().includes(termo))&&(f==="todos"||f==="erradas"&&x.correta===false||f==="corretas"&&x.correta===true||f==="branco"&&x.correta===null))}
  function renderHistorico(){const b=$("#lista-historico");if(!b)return;const l=filtrados();b.innerHTML=l.length?l.map(x=>`<article><div class="historico-topo"><div><strong class="${x.correta===true?"status-correto":x.correta===false?"status-errado":""}">${x.correta===true?"CORRETA":x.correta===false?"ERRADA":"EM BRANCO"}</strong><div class="historico-meta"><span>${esc(x.materia)}</span><span>${esc(x.assunto)}</span><span>${new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.criado_em))}</span></div></div>${x.marcada_revisao?'<span class="etiqueta">Revisar</span>':""}</div><p>${esc(x.enunciado)}</p><small><b>Sua resposta:</b> ${esc(x.texto_resposta||"Não respondida")}<br><b>Correta:</b> ${esc(x.texto_correta)}</small><button class="botao secundario botao-revisar-registro" type="button" data-revisar-id="${esc(x.id)}">Revisar esta questão</button></article>`).join(""):'<p class="vazio">Nenhum registro encontrado.</p>'}
  function abrirRevisao(id){const r=historico.find(x=>String(x.id)===String(id));if(!r)return;document.querySelectorAll(".tela").forEach(t=>t.hidden=true);$("#revisao-historico").hidden=false;document.querySelectorAll(".menu__item").forEach(b=>b.classList.remove("ativo"));$("#revisao-historico-titulo").textContent=`${r.materia} — ${r.assunto}`;$("#revisao-historico-meta").innerHTML=`<span>${esc(r.materia)}</span><span>${esc(r.assunto)}</span><span>${new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(r.criado_em))}</span>${r.marcada_revisao?'<span class="etiqueta">Marcada para revisar</span>':""}`;$("#revisao-historico-enunciado").textContent=r.enunciado;const q=DADOS_SIMULADO.questoes.find(x=>String(x.id)===String(r.questao_id)),alts=q?.alternativas||[r.texto_resposta,r.texto_correta].filter(Boolean);$("#revisao-historico-alternativas").innerHTML=alts.map((t,i)=>{const correta=q?i===Number(r.alternativa_correta):t===r.texto_correta,marcada=q?i===Number(r.alternativa_marcada):t===r.texto_resposta,classe=marcada&&!correta?"errada":correta?"correta":marcada?"marcada-anterior":"";return`<div class="alternativa ${classe}"><span class="letra">${String.fromCharCode(65+i)}</span><span>${esc(t)}${marcada?" — sua marcação":""}${correta?" — correta":""}</span></div>`}).join("");const c=q?.comentario||"O comentário original não está mais no conjunto atual, mas sua resposta e o gabarito foram preservados.";const box=$("#revisao-historico-comentario");box.className=`comentario ${r.correta===true?"correto":"errado"}`;box.innerHTML=`<strong>${r.correta===true?"✓ CORRETA E APROVADA":r.correta===false?"✕ ERRADA":"EM BRANCO"}</strong><p>${esc(c)}</p>`;window.scrollTo({top:0,behavior:"smooth"})}
  async function carregar(){const{data:s}=await db.auth.getSession();if(!s.session?.user)return;const desde=new Date();desde.setMonth(desde.getMonth()-6);const[{data:ts},{data:hs}]=await Promise.all([db.from("tentativas_simulado").select("*").gte("concluido_em",desde.toISOString()).order("concluido_em",{ascending:false}),db.from("historico_questoes").select("*").gte("criado_em",desde.toISOString()).order("criado_em",{ascending:false})]);tentativas=ts||[];historico=hs||[];renderHoje();renderGerais();renderHistorico();aplicarMarcadas()}
  renderRecursos();new MutationObserver(aplicarMarcadas).observe($("#grade-questoes"),{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});window.addEventListener("simulador:progresso",()=>setTimeout(aplicarMarcadas,20));window.addEventListener("dashboard:carregar",()=>setTimeout(carregar,80));window.addEventListener("historico:carregar",()=>setTimeout(carregar,80));$("#busca-historico").addEventListener("input",()=>setTimeout(renderHistorico,0));$("#filtro-resultado").addEventListener("change",()=>setTimeout(renderHistorico,0));$("#lista-historico").addEventListener("click",e=>{const b=e.target.closest("[data-revisar-id]");if(b)abrirRevisao(b.dataset.revisarId)});$("#voltar-historico").addEventListener("click",()=>window.Simulador?.mostrarTela("historico"));db.auth.onAuthStateChange((_e,s)=>{if(s?.user)setTimeout(carregar,150)});setTimeout(carregar,300);
})();