(() => {
  "use strict";
  const CHAVE_TEMA="simulador_tema",CHAVE_PROGRESSO=`simulador_${DADOS_SIMULADO.identificador}`,$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
  const estado={questoes:[],indice:0,respostas:{},marcadas:[],modo:"estudo",segundos:0,finalizado:false,intervalo:null,iniciadoEm:null};
  const telas=["dashboard","inicio","simulado","resultado","historico"];
  const el={totalInicial:$("#total-inicial"),iniciar:$("#botao-iniciar"),continuar:$("#botao-continuar"),tema:$("#botao-tema"),embaralharQuestoes:$("#embaralhar-questoes"),embaralharAlternativas:$("#embaralhar-alternativas"),grade:$("#grade-questoes"),textoProgresso:$("#texto-progresso"),barraProgresso:$("#barra-progresso"),respondidas:$("#respondidas"),restantes:$("#restantes"),tempo:$("#tempo"),materia:$("#materia"),tituloQuestao:$("#titulo-questao"),assunto:$("#assunto"),origem:$("#origem"),enunciado:$("#enunciado"),alternativas:$("#alternativas"),comentario:$("#comentario"),tituloComentario:$("#titulo-comentario"),textoComentario:$("#texto-comentario"),anterior:$("#anterior"),limpar:$("#limpar"),proxima:$("#proxima"),revisao:$("#botao-revisao"),finalizar:$("#botao-finalizar"),resultadoTitulo:$("#resultado-titulo"),resultadoMensagem:$("#resultado-mensagem"),percentual:$("#percentual"),circulo:$("#circulo"),total:$("#total"),acertos:$("#acertos"),erros:$("#erros"),branco:$("#branco"),tempoFinal:$("#tempo-final"),listaRevisao:$("#lista-revisao"),imprimir:$("#imprimir"),reiniciar:$("#reiniciar"),reiniciarProva:$("#botao-reiniciar-prova"),aviso:$("#aviso")};
  function mostrarTela(id){telas.forEach(t=>{const x=$("#"+t);if(x)x.hidden=t!==id});$$('[data-tela]').forEach(b=>b.classList.toggle("ativo",b.dataset.tela===id));window.scrollTo({top:0,behavior:"smooth"});if(id==="dashboard")window.dispatchEvent(new CustomEvent("dashboard:carregar"));if(id==="historico")window.dispatchEvent(new CustomEvent("historico:carregar"))}
  window.mostrarTela=mostrarTela;
  function copiarQuestoes(){return DADOS_SIMULADO.questoes.map(q=>({...q,alternativas:q.alternativas.map((texto,original)=>({texto,original}))}))}
  function embaralhar(lista){const c=[...lista];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
  function iniciarNovo(){estado.questoes=copiarQuestoes();estado.indice=0;estado.respostas={};estado.marcadas=[];estado.segundos=0;estado.finalizado=false;estado.iniciadoEm=new Date().toISOString();estado.modo=$("input[name=modo]:checked")?.value||"estudo";if(el.embaralharQuestoes.checked)estado.questoes=embaralhar(estado.questoes);if(el.embaralharAlternativas.checked)estado.questoes=estado.questoes.map(q=>({...q,alternativas:embaralhar(q.alternativas)}));salvar();abrirSimulado()}
  function abrirSimulado(){mostrarTela("simulado");criarGrade();renderizar();iniciarCronometro()}
  function criarGrade(){el.grade.innerHTML="";estado.questoes.forEach((_,i)=>{const b=document.createElement("button");b.type="button";b.className="numero";b.textContent=i+1;b.onclick=()=>{estado.indice=i;renderizar()};el.grade.appendChild(b)})}
  function renderizar(){const q=estado.questoes[estado.indice];if(!q)return;const r=estado.respostas[q.id];el.materia.textContent=q.materia||"Geral";el.tituloQuestao.textContent=`Questão ${estado.indice+1}`;el.assunto.textContent=q.assunto||"Assunto não informado";el.origem.textContent=q.origem||"Origem não informada";el.enunciado.innerHTML=q.enunciado;el.alternativas.innerHTML="";el.comentario.hidden=true;el.comentario.className="comentario";q.alternativas.forEach((a,i)=>{const b=document.createElement("button");b.type="button";b.className="alternativa";b.innerHTML=`<span class="letra">${String.fromCharCode(65+i)}</span><span>${esc(a.texto)}</span>`;if(r===a.original)b.classList.add("selecionada");const corrigir=estado.finalizado||(estado.modo==="estudo"&&r!==undefined);if(corrigir){b.disabled=true;if(a.original===q.respostaCorreta)b.classList.add("correta");if(r===a.original&&a.original!==q.respostaCorreta)b.classList.add("errada")}else b.onclick=()=>responder(a.original);el.alternativas.appendChild(b)});if(r!==undefined&&(estado.modo==="estudo"||estado.finalizado))mostrarComentario(q,r);const marcada=estado.marcadas.includes(q.id);el.revisao.textContent=marcada?"★ Marcada para revisar":"☆ Marcar para revisar";el.anterior.disabled=estado.indice===0;el.proxima.textContent=estado.indice===estado.questoes.length-1?"Finalizar":"Próxima →";atualizarResumo();atualizarGrade()}
  function responder(indice){const q=estado.questoes[estado.indice];estado.respostas[q.id]=indice;salvar();renderizar()}
  function mostrarComentario(q,r){const acertou=r===q.respostaCorreta;el.comentario.hidden=false;el.comentario.classList.add(acertou?"correto":"errado");el.tituloComentario.textContent=acertou?"✓ Resposta correta e aprovada":"✕ Resposta errada";el.textoComentario.textContent=q.comentario||"Sem comentário disponível."}
  function atualizarResumo(){const total=estado.questoes.length,resp=Object.keys(estado.respostas).length;el.textoProgresso.textContent=`${resp} de ${total}`;el.barraProgresso.style.width=`${total?resp/total*100:0}%`;el.respondidas.textContent=resp;el.restantes.textContent=total-resp;el.tempo.textContent=formatarTempo(estado.segundos)}
  function atualizarGrade(){$$(".numero").forEach((b,i)=>{const q=estado.questoes[i],r=estado.respostas[q.id];b.className="numero";if(r!==undefined)b.classList.add("respondida");if(estado.marcadas.includes(q.id))b.classList.add("marcada");if(estado.finalizado||(estado.modo==="estudo"&&r!==undefined)){b.classList.remove("respondida");b.classList.add(r===q.respostaCorreta?"correta":"errada")}if(i===estado.indice)b.classList.add("atual")})}
  function proxima(){if(estado.indice<estado.questoes.length-1){estado.indice++;salvar();renderizar();window.scrollTo({top:0,behavior:"smooth"})}else confirmarFinalizacao()}
  function anterior(){if(estado.indice>0){estado.indice--;salvar();renderizar()}}
  function limpar(){const q=estado.questoes[estado.indice];if(estado.modo==="estudo"&&estado.respostas[q.id]!==undefined)return avisar("No modo estudo, uma resposta corrigida não pode ser apagada.");delete estado.respostas[q.id];salvar();renderizar()}
  function marcar(){const id=estado.questoes[estado.indice].id,p=estado.marcadas.indexOf(id);p>=0?estado.marcadas.splice(p,1):estado.marcadas.push(id);salvar();renderizar()}
  function confirmarFinalizacao(){const faltam=estado.questoes.length-Object.keys(estado.respostas).length;if(confirm(faltam?`Ainda existem ${faltam} questão(ões) sem resposta. Finalizar mesmo assim?`:"Finalizar e registrar o resultado?"))finalizar()}
  function calcular(){let acertos=0,erros=0,branco=0;estado.questoes.forEach(q=>{const r=estado.respostas[q.id];if(r===undefined)branco++;else if(r===q.respostaCorreta)acertos++;else erros++});const total=estado.questoes.length;return{total,acertos,erros,branco,percentual:total?Math.round(acertos/total*100):0}}
  function finalizar(){if(estado.finalizado)return mostrarResultado();estado.finalizado=true;pararCronometro();salvar();const resultado=calcular();window.dispatchEvent(new CustomEvent("simulador:finalizado",{detail:{estado:JSON.parse(JSON.stringify(estado)),resultado}}));mostrarResultado()}
  function mostrarResultado(){const r=calcular();mostrarTela("resultado");el.resultadoTitulo.textContent=r.percentual>=90?"Excelente desempenho!":r.percentual>=75?"Muito bom resultado!":r.percentual>=60?"Você está no caminho certo.":"Hora de reforçar a revisão.";el.resultadoMensagem.textContent=r.percentual>=75?"Revise os pontos errados para consolidar o aprendizado.":"Use a análise abaixo para priorizar seus próximos estudos.";el.percentual.textContent=`${r.percentual}%`;el.circulo.style.setProperty("--p",r.percentual);el.total.textContent=r.total;el.acertos.textContent=r.acertos;el.erros.textContent=r.erros;el.branco.textContent=r.branco;el.tempoFinal.textContent=formatarTempo(estado.segundos);renderizarRevisao("todas")}
  function renderizarRevisao(filtro){el.listaRevisao.innerHTML="";const lista=estado.questoes.filter(q=>filtro==="erradas"?estado.respostas[q.id]!==q.respostaCorreta:filtro==="marcadas"?estado.marcadas.includes(q.id):true);if(!lista.length){el.listaRevisao.innerHTML='<p class="vazio">Nenhuma questão neste filtro.</p>';return}lista.forEach(q=>{const r=estado.respostas[q.id],status=r===q.respostaCorreta?"correta":"errada",rotulo=r===q.respostaCorreta?"CORRETA E APROVADA":r===undefined?"EM BRANCO":"ERRADA";const item=document.createElement("article");item.className=`item-revisao ${status}`;item.innerHTML=`<strong class="resultado-forte">${rotulo}</strong><p><b>${esc(q.materia)} · ${esc(q.assunto||"")}</b></p><p>${esc(extrairTexto(q.enunciado))}</p><small><b>Sua resposta:</b> ${esc(r===undefined?"Não respondida":textoAlternativa(q,r))}<br><b>Resposta correta:</b> ${esc(textoAlternativa(q,q.respostaCorreta))}<br><b>Comentário:</b> ${esc(q.comentario||"Sem comentário.")}</small>`;el.listaRevisao.appendChild(item)})}
  function textoAlternativa(q,o){return q.alternativas.find(a=>a.original===o)?.texto||"Alternativa não encontrada"}
  function salvar(){const dados={questoes:estado.questoes,indice:estado.indice,respostas:estado.respostas,marcadas:estado.marcadas,modo:estado.modo,segundos:estado.segundos,finalizado:estado.finalizado,iniciadoEm:estado.iniciadoEm};localStorage.setItem(CHAVE_PROGRESSO,JSON.stringify(dados));el.continuar.hidden=false;window.dispatchEvent(new CustomEvent("simulador:progresso",{detail:dados}))}
  function carregar(){try{const d=JSON.parse(localStorage.getItem(CHAVE_PROGRESSO));if(!d?.questoes?.length)return;Object.assign(estado,d);estado.finalizado?mostrarResultado():abrirSimulado()}catch{avisar("Não foi possível carregar o progresso.")}}
  function reiniciar(){if(!confirm("Apagar o progresso atual e começar novamente?"))return;localStorage.removeItem(CHAVE_PROGRESSO);pararCronometro();window.dispatchEvent(new CustomEvent("simulador:reiniciar"));estado.questoes=[];estado.respostas={};estado.marcadas=[];estado.finalizado=false;el.continuar.hidden=true;mostrarTela("inicio")}
  function iniciarCronometro(){pararCronometro();estado.intervalo=setInterval(()=>{estado.segundos++;el.tempo.textContent=formatarTempo(estado.segundos);if(estado.segundos%10===0)salvar()},1000)}function pararCronometro(){if(estado.intervalo)clearInterval(estado.intervalo);estado.intervalo=null}function formatarTempo(s){const h=Math.floor(s/3600),m=Math.floor(s%3600/60),seg=s%60;return(h?`${String(h).padStart(2,"0")}:`:"")+`${String(m).padStart(2,"0")}:${String(seg).padStart(2,"0")}`}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function extrairTexto(html){const d=document.createElement("div");d.innerHTML=html;return d.textContent?.trim()||""}function avisar(m){el.aviso.textContent=m;el.aviso.classList.add("visivel");setTimeout(()=>el.aviso.classList.remove("visivel"),2600)}
  el.totalInicial.textContent=DADOS_SIMULADO.questoes.length;$("#titulo-simulado-home").textContent=DADOS_SIMULADO.titulo;$("#data-atual").textContent=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(new Date());document.documentElement.dataset.tema=localStorage.getItem(CHAVE_TEMA)||"claro";el.continuar.hidden=!localStorage.getItem(CHAVE_PROGRESSO);
  $$('[data-tela]').forEach(b=>b.addEventListener("click",()=>mostrarTela(b.dataset.tela)));$("#ir-dashboard").onclick=()=>mostrarTela("dashboard");$("#voltar-dashboard").onclick=()=>mostrarTela("dashboard");el.iniciar.onclick=iniciarNovo;el.continuar.onclick=carregar;el.tema.onclick=()=>{const n=document.documentElement.dataset.tema==="escuro"?"claro":"escuro";document.documentElement.dataset.tema=n;localStorage.setItem(CHAVE_TEMA,n)};el.anterior.onclick=anterior;el.proxima.onclick=proxima;el.limpar.onclick=limpar;el.revisao.onclick=marcar;el.finalizar.onclick=confirmarFinalizacao;el.reiniciar.onclick=reiniciar;el.reiniciarProva.onclick=reiniciar;el.imprimir.onclick=()=>print();$$('.filtro').forEach(b=>b.onclick=()=>{$$('.filtro').forEach(x=>x.classList.remove("ativo"));b.classList.add("ativo");renderizarRevisao(b.dataset.filtro)});
  window.Simulador={CHAVE_PROGRESSO,copiarQuestoes,mostrarTela};
})();